### ISSUE TITLE
Present date picker on input field focus

### ISSUE THREAD

**Issue by gabro** [buildo/react-semantic-datepicker#4]
(Optionally) open the date picker when the input field takes focus.

I'm thinking of a prop on `DatePickerInput` along the lines of `presentPickerOnFocus` which defaults to `false`.

Thoughts, @FrancescoCioria ?

**Comment by gabro** [comment]
Closed by 67fe87973c00d21f2bf119a29788e26ef8aadc09

**Comment by nuflowx** [comment]
I appreciate the implementation which were made here, but unless I'm missing something obvious it doesn't seem to handle focus/blur at all.

Clicking works great, but when tab between fields it's very inconvenient that the datepicker doesn't show up.
