### ISSUE TITLE
New build system based on karma/webpack/babel

### ISSUE THREAD

**Issue by gabro** [buildo/react-semantic-datepicker#8]
Work in progress. Key points are

- [x] run in a real browser
  - Chrome by default, Firefox on Travis
- [ ] allow for breakpoints in sourcemaps
- [x] run tests on source (now it's on build)
- [ ] test coverage reports on coverall.io

**Comment by FrancescoCioria** [comment]
I refactored the project structure which is now based on web-lib-seed. What about coverage and CI?

**Comment by gabro** [comment]
I'll take care of it. Closing this in favor of https://github.com/buildo/react-semantic-datepicker/issues/11
